// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock_storage_test.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AddTask mocks base method.
func (m *MockStorage) AddTask(task *Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTask", task)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTask indicates an expected call of AddTask.
func (mr *MockStorageMockRecorder) AddTask(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockStorage)(nil).AddTask), task)
}

// CreateAsync mocks base method.
func (m *MockStorage) CreateAsync(task *Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateAsync", task)
}

// CreateAsync indicates an expected call of CreateAsync.
func (mr *MockStorageMockRecorder) CreateAsync(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAsync", reflect.TypeOf((*MockStorage)(nil).CreateAsync), task)
}

// DeleteAsync mocks base method.
func (m *MockStorage) DeleteAsync(uid string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteAsync", uid)
}

// DeleteAsync indicates an expected call of DeleteAsync.
func (mr *MockStorageMockRecorder) DeleteAsync(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAsync", reflect.TypeOf((*MockStorage)(nil).DeleteAsync), uid)
}

// DeleteTask mocks base method.
func (m *MockStorage) DeleteTask(uid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockStorageMockRecorder) DeleteTask(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockStorage)(nil).DeleteTask), uid)
}

// GetTask mocks base method.
func (m *MockStorage) GetTask(uid string) (*Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", uid)
	ret0, _ := ret[0].(*Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockStorageMockRecorder) GetTask(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockStorage)(nil).GetTask), uid)
}

// PendingAsyncOperations mocks base method.
func (m *MockStorage) PendingAsyncOperations() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingAsyncOperations")
	ret0, _ := ret[0].(int)
	return ret0
}

// PendingAsyncOperations indicates an expected call of PendingAsyncOperations.
func (mr *MockStorageMockRecorder) PendingAsyncOperations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingAsyncOperations", reflect.TypeOf((*MockStorage)(nil).PendingAsyncOperations))
}
