// Code generated by MockGen. DO NOT EDIT.
// Source: task.go
//
// Generated by this command:
//
//	mockgen -source=task.go -destination=mock_task_storage_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskStorage is a mock of TaskStorage interface.
type MockTaskStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStorageMockRecorder
	isgomock struct{}
}

// MockTaskStorageMockRecorder is the mock recorder for MockTaskStorage.
type MockTaskStorageMockRecorder struct {
	mock *MockTaskStorage
}

// NewMockTaskStorage creates a new mock instance.
func NewMockTaskStorage(ctrl *gomock.Controller) *MockTaskStorage {
	mock := &MockTaskStorage{ctrl: ctrl}
	mock.recorder = &MockTaskStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStorage) EXPECT() *MockTaskStorageMockRecorder {
	return m.recorder
}

// AddTask mocks base method.
func (m *MockTaskStorage) AddTask(task *Task) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddTask", task)
}

// AddTask indicates an expected call of AddTask.
func (mr *MockTaskStorageMockRecorder) AddTask(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTask", reflect.TypeOf((*MockTaskStorage)(nil).AddTask), task)
}

// DeleteTask mocks base method.
func (m *MockTaskStorage) DeleteTask(uid string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteTask", uid)
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskStorageMockRecorder) DeleteTask(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskStorage)(nil).DeleteTask), uid)
}

// GetTask mocks base method.
func (m *MockTaskStorage) GetTask(uid string) (*Task, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", uid)
	ret0, _ := ret[0].(*Task)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskStorageMockRecorder) GetTask(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskStorage)(nil).GetTask), uid)
}
